/* ============================================================
   content.js — ITEMS & PERKS (the Nubby brain of the game)
   Items live in your top inventory and trigger on events.
   Perks are powerful global modifiers chosen on perk rounds.

   Passive numeric fields the engine aggregates (summed):
     mult, paddleScale, ballScale, speedScale, extraBalls,
     coinMult, pierceChance, comboPow, revive, startBalls,
     shopDiscount, goldChance, bombChance, memeChance,
     critChance, coinBrickChance, quotaCut
   Flag fields (any-true): comboGain, laser, magnet, freeReroll, comboKeep
   Hook fields (functions): onBrickBreak, onScore, onLaunch,
     onBallLost, onRoundStart, onQuota, onCashOut
   Hooks talk to the engine through the global GAME helper API.
   ============================================================ */
(function (global) {
  'use strict';
  const R = () => Math.random();

  const ITEMS = [
    // ---------- COMMON ----------
    { id:'doge', name:'Doge', art:'doge', rarity:'common', price:4,
      mult:0.30, desc:'+0.30x to your NUMBER multiplier.', flavor:'much score · very number · wow' },
    { id:'pepe', name:'Sad Pepe', art:'pepe', rarity:'common', price:3,
      desc:'Every brick worth +3 flat. feelsgoodman.', flavor:'feels good man',
      onBrickBreak:(G,e)=>{ e.bonus += 3; } },
    { id:'coin', name:'Doubloon', art:'coin', rarity:'common', price:3,
      desc:'+2 NUBBINS every time you cash out.', flavor:'money money money',
      onCashOut:(G,e)=>{ e.coins += 2; } },
    { id:'shrek', name:'Shrek', art:'shrek', rarity:'common', price:4,
      paddleScale:0.30, desc:'Paddle 30% wider. It is all ogre now.', flavor:'get out of me swamp' },
    { id:'chungus', name:'Big Chungus', art:'chungus', rarity:'common', price:4,
      ballScale:0.45, desc:'Ball 45% chonkier — smash more bricks.', flavor:'absolute unit' },
    { id:'cheems', name:'Cheems', art:'cheems', rarity:'common', price:3,
      ballScale:0.30, desc:'+30% ball size. bonk.', flavor:'he do be bonkin' },
    { id:'wojak', name:'Wojak', art:'wojak', rarity:'common', price:3,
      desc:'When a ball drains, earn +1 NUBBIN. feel the pain, get paid.', flavor:'i know that feel',
      onBallLost:(G,e)=>{ G.coins += 1; } },
    { id:'isthisapigeon', name:'Is This A Pigeon', art:'isthisapigeon', rarity:'common', price:4,
      comboGain:true, comboPow:0.03, desc:'Combo multiplier scaling (+0.03x / brick, resets on paddle).', flavor:'is this a pigeon?' },
    { id:'badluckbrian', name:'Bad Luck Brian', art:'badluckbrian', rarity:'common', price:2,
      mult:0.22, desc:'Dirt cheap +0.22x multiplier. oof.', flavor:'tries his best' },
    { id:'picardfacepalm', name:'Picard Facepalm', art:'picardfacepalm', rarity:'common', price:3,
      freeReroll:true, desc:'Shop rerolls are FREE. *facepalm*', flavor:'make it so' },

    // ---------- RARE ----------
    { id:'datboi', name:'Dat Boi', art:'datboi', rarity:'rare', price:6,
      extraBalls:1, desc:'+1 extra ball every single launch.', flavor:'here come dat boi · o shit waddup' },
    { id:'pingas', name:'Pingas', art:'pingas', rarity:'rare', price:5,
      desc:'14% chance per brick to spit out a NUBBIN coin.', flavor:'P-I-N-G-A-S',
      onBrickBreak:(G,e)=>{ if (R()<0.14) GAME.spawnCoinAt(e.brick.x, e.brick.y, 1); } },
    { id:'stonks', name:'Stonks', art:'stonks', rarity:'rare', price:6,
      coinMult:0.5, desc:'+50% NUBBINS on cash out. number only go up.', flavor:'stonks' },
    { id:'sanic', name:'Sanic', art:'sanic', rarity:'rare', price:5,
      speedScale:0.25, mult:0.20, desc:'Ball +25% speed & +0.20x mult. gotta go fast.', flavor:'gotta go fast' },
    { id:'surprisedpikachu', name:'Surprised Pikachu', art:'surprisedpikachu', rarity:'rare', price:5,
      critChance:0.10, desc:'10% of bricks CRIT for x5. shocking.', flavor:'!!!' },
    { id:'mockingspongebob', name:'Mocking SpongeBob', art:'mockingspongebob', rarity:'rare', price:5,
      memeChance:0.13, desc:'Way more meme bricks → way more flashes.', flavor:'sUcH bReAk' },
    { id:'drake', name:'Drake', art:'drake', rarity:'rare', price:6,
      coinMult:0.4, goldChance:0.05, desc:'Nah cheap bricks. Yeah gold. +40% coins, more gold bricks.', flavor:'nah... yeah' },
    { id:'rollsafe', name:'Roll Safe', art:'rollsafe', rarity:'rare', price:5,
      paddleScale:0.25, quotaCut:0.08, desc:'+25% paddle, -8% quota. big brain.', flavor:"can't lose if you aim" },
    { id:'saltbae', name:'Salt Bae', art:'saltbae', rarity:'rare', price:6,
      critChance:0.08, mult:0.15, desc:'Sprinkle crits: +8% crit, +0.15x mult.', flavor:'*sprinkle*' },
    { id:'successkid', name:'Success Kid', art:'successkid', rarity:'rare', price:5,
      desc:'The moment you hit quota, +3 NUBBINS. nailed it.', flavor:'all according to keikaku',
      onQuota:(G)=>{ G.coins += 3; GAME.toast('NAILED IT +3'); } },
    { id:'philosoraptor', name:'Philosoraptor', art:'philosoraptor', rarity:'rare', price:5,
      coinBrickChance:0.06, desc:'6% of bricks drop a coin. deep thoughts.', flavor:'what if money' },
    { id:'distractedbf', name:'Distracted Boyfriend', art:'distractedbf', rarity:'rare', price:5,
      pierceChance:0.18, desc:'Ball gets distracted & phases through bricks (18%).', flavor:'wandering eye' },
    { id:'thisisfine', name:'This Is Fine', art:'thisisfine', rarity:'rare', price:6,
      desc:'When a ball drains, 45% chance to refund it.', flavor:'this is fine.',
      onBallLost:(G,e)=>{ if (!e.save && R()<0.45){ e.save = true; GAME.toast('THIS IS FINE 🔥'); } } },
    { id:'harold', name:'Hide The Pain Harold', art:'harold', rarity:'rare', price:5,
      desc:'35% chance to refund a drained ball. (he is fine.)', flavor:"i'm fine",
      onBallLost:(G,e)=>{ if (!e.save && R()<0.35){ e.save = true; GAME.toast("i'm fine 🙂"); } } },
    { id:'amogus', name:'Amogus', art:'amogus', rarity:'rare', price:6,
      desc:'Each round one random brick becomes SUS (worth x8).', flavor:'kinda sus',
      onRoundStart:(G)=>{ GAME.markSuperBrick(8); } },
    { id:'ancientaliens', name:'Ancient Aliens', art:'ancientaliens', rarity:'rare', price:6,
      memeChance:0.08, critChance:0.05, desc:"More memes & crits. i'm not saying it's aliens, but…", flavor:'aliens' },
    { id:'bonk', name:'Bonk', art:'bonk', rarity:'rare', price:5,
      comboKeep:true, desc:'Combo NO LONGER resets on the paddle. go to horny jail.', flavor:'bonk' },

    // ---------- EPIC ----------
    { id:'over9000', name:'Over 9000', art:'over9000', rarity:'epic', price:9,
      desc:'When your NUMBER passes 9000 in a round, NUKE the board for huge bonus. Once per round.', flavor:"IT'S OVER NINE THOUSAAAND!!",
      onScore:(G,e)=>{ if (!G._over9k && G.score >= 9000){ G._over9k = true; GAME.toast("IT'S OVER 9000!!! 💥"); SFX.over9000(); SFX.play('over9000'); GAME.explodeAllBricks(50); } } },
    { id:'trollface', name:'Troll Face', art:'trollface', rarity:'epic', price:7,
      desc:'Gamble: 32% of bricks pay x3, 14% pay nothing. problem?', flavor:'u mad bro?',
      onBrickBreak:(G,e)=>{ const r=R(); if(r<0.32) e.multAdd+=2; else if(r<0.46) e.bonus=-e.base; } },
    { id:'nyan', name:'Nyan Cat', art:'nyan', rarity:'epic', price:8,
      pierceChance:0.40, desc:'40% chance the ball PHASES through a brick (no bounce). nyan~', flavor:'nyanyanyanyan' },
    { id:'galaxybrain', name:'Galaxy Brain', art:'galaxybrain', rarity:'epic', price:8,
      comboGain:true, comboPow:0.04, desc:'Combo multiplier grows +0.04x per brick — resets on the paddle. ascend.', flavor:'expanding brain' },
    { id:'mlg', name:'MLG 420', art:'mlg', rarity:'epic', price:8,
      laser:true, desc:'CLICK to fire dual lasers from your paddle. 360 noscope.', flavor:'wombo combo' },
    { id:'dealwithit', name:'Deal With It', art:'dealwithit', rarity:'epic', price:8,
      laser:true, mult:0.2, desc:'Paddle lasers + 0.2x mult. ( •_•)>⌐■-■', flavor:'deal with it' },
    { id:'gigachad', name:'Gigachad', art:'gigachad', rarity:'epic', price:8,
      mult:0.5, desc:'+0.5x multiplier. pure sigma energy.', flavor:'yes. i grind.' },
    { id:'coffindance', name:'Coffin Dance', art:'coffindance', rarity:'epic', price:7,
      desc:'When a ball dies, the pallbearers pay you +4 NUBBINS.', flavor:'astronomia',
      onBallLost:(G,e)=>{ G.coins += 4; GAME.toast('⚰️ +4 ⚰️'); } },
    { id:'womanyellingcat', name:'Woman Yelling at Cat', art:'womanyellingcat', rarity:'epic', price:7,
      desc:'20% chance a brick is DOUBLED. smudge approves.', flavor:'smudge says no',
      onBrickBreak:(G,e)=>{ if (R()<0.20) e.multAdd += 1; } },
    { id:'evilkermit', name:'Evil Kermit', art:'evilkermit', rarity:'epic', price:7,
      bombChance:0.10, desc:'More bomb bricks → chain explosions. do it.', flavor:'me to me' },
    { id:'grusplan', name:"Gru's Plan", art:'grusplan', rarity:'epic', price:7,
      quotaCut:0.18, desc:'-18% quota. wait… that is actually good.', flavor:'the plan' },
    { id:'boromir', name:'One Does Not Simply', art:'boromir', rarity:'epic', price:7,
      magnet:true, desc:'Coins are drawn to your paddle. one does not simply miss loot.', flavor:'…walk into Mordor' },

    // ---------- LEGENDARY ----------
    { id:'rickroll', name:'Rickroll', art:'rickroll', rarity:'legendary', price:10,
      revive:1, desc:'Once per run, when you would lose, REVIVE with fresh balls. never gonna give you up.', flavor:'never gonna let you down' },
    { id:'thanos', name:'Perfectly Balanced', art:'thanos', rarity:'legendary', price:11,
      mult:0.75, startBalls:-1, desc:'+0.75x multiplier, but -1 max ball. perfectly balanced.', flavor:'as all things should be' },

    // ---------- v3: NEW MEME LORDS ----------
    { id:'windowsxp', name:'Windows XP', art:'windowsxp', rarity:'common', price:4,
      mult:0.25, desc:'+0.25x multiplier. it just works (usually).', flavor:'bliss' },
    { id:'sadviolin', name:'Sad Violin', art:'sadviolin', rarity:'common', price:3,
      coinMult:0.3, desc:"+30% NUBBINS. someone's getting paid.", flavor:'world\'s smallest violin' },
    { id:'johncena', name:'John Cena', art:'johncena', rarity:'rare', price:6,
      extraBalls:1, desc:'+1 ball. AND HIS NAME IS... you can\'t see it coming.', flavor:'bing bong bong bong' },
    { id:'nokia', name:'Nokia 3310', art:'nokia', rarity:'rare', price:5,
      desc:'Indestructible: 30% chance to refund a drained ball.', flavor:'unbreakable',
      onBallLost:(G,e)=>{ if (!e.save && R()<0.30){ e.save = true; GAME.toast('UNBREAKABLE 📱'); } } },
    { id:'illuminati', name:'Illuminati', art:'illuminati', rarity:'rare', price:6,
      memeChance:0.10, mult:0.15, desc:'More meme bricks + 0.15x. the truth is out there.', flavor:'confirmed' },
    { id:'crabrave', name:'Crab Rave', art:'crabrave', rarity:'rare', price:6,
      coinMult:0.6, desc:'🦀 +60% NUBBINS 🦀', flavor:'crab rave' },
    { id:'megamind', name:'Megamind', art:'megamind', rarity:'epic', price:7,
      quotaCut:0.10, mult:0.2, desc:'-10% quota & +0.2x. no bricks? no problem.', flavor:'no bitches?' },
    { id:'emotionaldamage', name:'Emotional Damage', art:'emotionaldamage', rarity:'epic', price:7,
      critChance:0.12, desc:'+12% crit chance. EMOTIONAL DAMAGE.', flavor:'emotional damage' },
    { id:'nani', name:'Omae Wa Mou', art:'nani', rarity:'epic', price:8,
      critChance:0.10, mult:0.3, desc:'+10% crit & +0.3x. you are already dead.', flavor:'NANI?!' },
    { id:'tobecontinued', name:'To Be Continued', art:'tobecontinued', rarity:'legendary', price:10,
      revive:1, desc:'An EXTRA revive. when you would lose… to be continued →', flavor:'roundabout' },
    { id:'wasted', name:'Wasted', art:'wasted', rarity:'legendary', price:10,
      mult:1.0, speedScale:0.2, desc:'+1.0x multiplier & faster ball. live fast.', flavor:'wasted' },

    // ---------- v5: CLASSIC YTP / CD-i + BADASS ----------
    { id:'starfox', name:'Star Fox', art:'starfox', rarity:'epic', price:8, laser:true,
      desc:"Paddle lasers. Can't let you do that, Star Fox!", flavor:"can't let you do that" },
    { id:'barrelroll', name:'Do A Barrel Roll', art:'barrelroll', rarity:'rare', price:6, pierceChance:0.30,
      desc:'30% chance the ball phases through bricks. do a barrel roll!', flavor:'use the boost to get through' },
    { id:'squadala', name:'Squadala', art:'squadala', rarity:'rare', price:5, speedScale:0.3,
      desc:"+30% ball speed. Squadala, we're off!", flavor:"we're off" },
    { id:'weegee', name:'Weegee', art:'weegee', rarity:'epic', price:7, mult:0.4,
      desc:'+0.4x multiplier. the stare pierces your soul.', flavor:'weegee' },
    { id:'mahboi', name:'Mah Boi', art:'mahboi', rarity:'common', price:4, paddleScale:0.4,
      desc:'+40% paddle width. this peace is what all true gamers strive for.', flavor:'mah boi' },
    { id:'ganon', name:'You Must Die', art:'ganon', rarity:'epic', price:7, critChance:0.12,
      desc:'+12% crit chance. YOU must DIE!', flavor:'gee it sure is boring around here' },
    { id:'spaghetti', name:'Spaghetti', art:'spaghetti', rarity:'rare', price:5, coinBrickChance:0.08,
      desc:'8% of bricks drop coins. mama mia, spaghetti!', flavor:'spaghetti' },
    { id:'mamaluigi', name:'Mama Luigi', art:'mamaluigi', rarity:'rare', price:6, extraBalls:1,
      desc:'+1 extra ball every launch. mama luigi!', flavor:"that's-a no good" },
    { id:'immeen', name:'I.M. Meen', art:'immeen', rarity:'epic', price:7, memeChance:0.15,
      desc:'Way more meme bricks. an evil so foul…', flavor:'a book that you wrote' },
    { id:'mariohaha', name:'Mario Haha', art:'mariohaha', rarity:'common', price:4, mult:0.3,
      desc:'+0.3x multiplier. haha!', flavor:"it's-a me" },
    { id:'heehee', name:'Hee Hee', art:'heehee', rarity:'common', price:3, coinMult:0.5,
      desc:'+50% NUBBINS. hee hee!', flavor:'shamone' },
    { id:'sparta', name:'This Is Sparta', art:'sparta', rarity:'epic', price:8, ballScale:0.4, mult:0.2,
      desc:'+40% ball size & +0.2x. THIS. IS. SPARTA!', flavor:'*kick*' },
    { id:'doomguy', name:'Doom Guy', art:'doomguy', rarity:'legendary', price:10, mult:0.6,
      desc:'+0.6x multiplier. rip and tear, until it is done.', flavor:'rip and tear' },
    { id:'leeroy', name:'Leeroy Jenkins', art:'leeroy', rarity:'epic', price:7, extraBalls:2, startBalls:-1,
      desc:'+2 balls per launch, but -1 max ball. at least he has chicken.', flavor:'LEEEROY!' },
    { id:'shia', name:'Just Do It', art:'shia', rarity:'rare', price:6, comboGain:true, comboPow:0.05,
      desc:'Combo scaling (+0.05x/brick). JUST DO IT!', flavor:"don't let your dreams be dreams" },
    { id:'ugandanknuckles', name:'Ugandan Knuckles', art:'ugandanknuckles', rarity:'rare', price:6, magnet:true,
      desc:'Coins home to your paddle. do you know de way?', flavor:'ebola ebola' },
    { id:'immaheadout', name:'Imma Head Out', art:'immaheadout', rarity:'rare', price:5,
      desc:'40% chance to refund a drained ball. ight, imma head out.', flavor:'*gets up*',
      onBallLost:(G,e)=>{ if(!e.save && R()<0.40){ e.save=true; GAME.toast('IGHT IMMA HEAD OUT'); } } },
    { id:'skibidi', name:'Skibidi Toilet', art:'skibidi', rarity:'epic', price:7, memeChance:0.10, mult:0.2,
      desc:'More meme bricks + 0.2x. skibidi dop dop yes yes.', flavor:'brainrot' },
    { id:'grimace', name:'Grimace Shake', art:'grimace', rarity:'rare', price:5, ballScale:0.5,
      desc:'+50% ball size. *sips* …it was the grimace shake.', flavor:'birthday shake' },
    { id:'johnwick', name:'John Wick', art:'johnwick', rarity:'epic', price:8, critChance:0.15,
      desc:'+15% crit chance. yeah.', flavor:'the boogeyman' },
    { id:'therock', name:'The Rock', art:'therock', rarity:'rare', price:6, paddleScale:0.3, mult:0.2,
      desc:'+30% paddle & +0.2x. can you smell what the Rock is cookin?', flavor:'👁️👄👁️' },
    { id:'ohio', name:'Only In Ohio', art:'ohio', rarity:'epic', price:7,
      desc:'Gamble: 30% of bricks pay x3, 15% pay nothing. only in ohio.', flavor:'sus ohio rizz',
      onBrickBreak:(G,e)=>{ const r=R(); if(r<0.30) e.multAdd+=2; else if(r<0.45) e.bonus=-e.base; } },
    { id:'pressf', name:'Press F', art:'pressf', rarity:'legendary', price:10, revive:1,
      desc:'An extra revive. press F to pay respects.', flavor:'F' },
  ];

  const PERKS = [
    { id:'p_wow', name:'MUCH WOW', art:'doge', mult:0.6, desc:'+0.6x global NUMBER multiplier.', flavor:'so multiply' },
    { id:'p_army', name:'DAT BOI ARMY', art:'datboi', extraBalls:1, desc:'+1 extra ball every launch.', flavor:'dem bois multiply' },
    { id:'p_market', name:'STONKS MARKET', art:'stonks', coinMult:1.0, desc:'Double your NUBBINS on every cash out.', flavor:'to the moon' },
    { id:'p_unit', name:'ABSOLUTE UNIT', art:'chungus', paddleScale:0.6, ballScale:0.3, desc:'+60% paddle width, +30% ball size.', flavor:'lad' },
    { id:'p_galaxy', name:'GALAXY MODE', art:'galaxybrain', comboGain:true, comboPow:0.07, desc:'Combo multiplier scaling, supercharged (+0.07x/brick).', flavor:'transcend' },
    { id:'p_phase', name:'PHASE BALL', art:'nyan', pierceChance:0.5, desc:'+50% chance to phase the ball through bricks.', flavor:'nyan through walls' },
    { id:'p_nubby', name:'EXTRA NUBBY', art:'nubby', startBalls:2, desc:'+2 max balls per round.', flavor:'one of us' },
    { id:'p_glass', name:'GLASS CANNON', art:'over9000', mult:1.2, startBalls:-1, desc:'+1.2x multiplier, but -1 max ball. high risk, high meme.', flavor:'all in' },
    { id:'p_lucky', name:'LUCKY 7', art:'coin', shopDiscount:2, desc:'All shop items cost 2 NUBBINS less.', flavor:'jackpot' },
    { id:'p_laser', name:'NO SCOPE', art:'mlg', laser:true, desc:'Permanent paddle lasers — click to fire.', flavor:'mlg pro' },
    // ---- new ----
    { id:'p_crit', name:'SHOCK THERAPY', art:'surprisedpikachu', critChance:0.15, desc:'+15% crit chance (bricks score x5).', flavor:'!!!' },
    { id:'p_meme', name:'MEME OVERLOAD', art:'mockingspongebob', memeChance:0.18, desc:'WAY more meme bricks → way more flashes. obnoxious.', flavor:'mAxImUm dAnK' },
    { id:'p_plan', name:'THE PLAN', art:'grusplan', quotaCut:0.25, desc:'-25% quota, forever.', flavor:"wait, that's good" },
    { id:'p_magnet', name:'LOOT GOBLIN', art:'boromir', magnet:true, coinMult:0.5, desc:'Coins home to your paddle + 50% more NUBBINS.', flavor:'gimme gimme' },
    { id:'p_gold', name:'GOLD RUSH', art:'drake', goldChance:0.12, desc:'Tons more gold bricks.', flavor:'bling bling' },
    { id:'p_bonk', name:'HORNY JAIL', art:'bonk', comboGain:true, comboKeep:true, comboPow:0.05, desc:'Combo scaling that NEVER resets on the paddle.', flavor:'bonk bonk bonk' },
    { id:'p_sigma', name:'SIGMA GRINDSET', art:'gigachad', mult:0.9, desc:'+0.9x global multiplier. grind harder.', flavor:'we go gym' },
    { id:'p_croissant', name:'DROPPED MY CROISSANT', art:'picardfacepalm', freeReroll:true, shopDiscount:1, desc:'Free shop rerolls + items cost 1 less.', flavor:'aw man' },
    { id:'p_xp', name:'IT JUST WORKS', art:'windowsxp', mult:0.7, desc:'+0.7x global multiplier.', flavor:'todd howard' },
    { id:'p_nani', name:'ALREADY DEAD', art:'nani', critChance:0.2, desc:'+20% crit chance.', flavor:'omae wa mou shindeiru' },
    { id:'p_crab', name:'CRAB RAVE', art:'crabrave', coinMult:1.0, magnet:true, desc:'🦀 Double NUBBINS + coins home to you 🦀', flavor:'he gone, do the crab' },
    { id:'p_sparta', name:'THIS IS SPARTA', art:'sparta', mult:0.4, ballScale:0.4, desc:'+0.4x mult & +40% ball size. *kick*', flavor:'madness? THIS. IS. SPARTA!' },
    { id:'p_doom', name:'RIP AND TEAR', art:'doomguy', mult:1.0, desc:'+1.0x global multiplier. until it is done.', flavor:'doom slayer' },
    { id:'p_leeroy', name:'LEEROY JENKINS', art:'leeroy', extraBalls:2, desc:'+2 extra balls every launch.', flavor:"at least i have chicken" },
  ];

  const byId = {};
  ITEMS.forEach(i => byId[i.id] = i);
  PERKS.forEach(p => byId[p.id] = p);

  global.CONTENT = {
    items: ITEMS,
    perks: PERKS,
    byId,
    sum(list, prop){ let s=0; for(const d of list) if(typeof d[prop]==='number') s+=d[prop]; return s; },
    prod(list, prop){ let p=1; for(const d of list) if(typeof d[prop]==='number') p*=(1+d[prop]); return p; },  // multiplicative stacking
    count(list, flag){ let n=0; for(const d of list) if(d[flag]) n++; return n; },
    any(list, flag){ for(const d of list) if(d[flag]) return true; return false; },
    maxProp(list, prop){ let m=0; for(const d of list) if(typeof d[prop]==='number'&&d[prop]>m) m=d[prop]; return m; },
  };
})(window);
